# Generated by Django 2.0.6 on 2018-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EIS_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.CharField(blank=True, default='Год', max_length=4)),
                ('period_month', models.CharField(blank=True, default='Месяц', max_length=10)),
                ('category', models.CharField(default='Без категории', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('tags', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('file_in_pdf', models.FileField(blank=True, upload_to='')),
                ('file_in', models.FileField(blank=True, upload_to='')),
                ('update_user', models.CharField(default='Аноним', max_length=200)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
