# Generated by Django 2.0.6 on 2018-07-06 05:59

import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20180706_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eis_archive',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='eis_archive',
            name='file',
            field=models.FileField(blank=True, upload_to=archives.models.rename_upload_file),
        ),
        migrations.AlterField(
            model_name='eis_archive',
            name='file_pdf',
            field=models.FileField(blank=True, upload_to=archives.models.rename_upload_file),
        ),
        migrations.AlterField(
            model_name='eis_archive',
            name='period_month',
            field=models.CharField(choices=[('00', 'Нет данных'), ('01', 'Январь'), ('02', 'Февраль'), ('03', 'Март'), ('04', 'Апрель'), ('05', 'Май'), ('06', 'Июнь'), ('07', 'Июль'), ('08', 'Август'), ('09', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eis_archive',
            name='period_year',
            field=models.CharField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], max_length=4),
        ),
    ]
